extends:
  # Default
  - spectral:oas
  # OWASP TOP 10 Security
  - "https://unpkg.com/@stoplight/spectral-owasp-ruleset/dist/ruleset.mjs"
  #  Documentation Rules
  - "https://unpkg.com/@stoplight/spectral-documentation/dist/ruleset.mjs"
  # Versioning
  - "https://unpkg.com/@stoplight/spectral-url-versioning/dist/ruleset.mjs"
  # Zalando Rules
  - "https://raw.githubusercontent.com/baloise-incubator/spectral-ruleset/main/zalando.yml"
rules:
  owasp:api2:2019-protection-global-unsafe: "off"
  owasp:api2:2019-protection-global-unsafe-strict: "off"
  owasp:api4:2019-rate-limit: "off"
  owasp:api4:2019-rate-limit-responses-429: "off"
